version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/conf/"
    schedule:
      interval: "weekly"
      day: "monday"
      timezone: "Etc/UTC"
    target-branch: "master"
    labels:
      - "pip"
      - "dependencies"
