name: CI
on:
  push:

jobs:
  ci:
    permissions:
      id-token: write
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::627003544259:role/github_actions_ecr_gbq-sender
          role-session-name: nikolay-zver-test
          aws-region: eu-central-1
          mask-aws-account-id: "no"