name: Dump context
on:
  push:
  release:
jobs:
  dump:
    environment: master
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        run: |
          echo '${{ toJSON(github) }}'
      - name: Test
        run: |
          echo '${{secrets.TEST}}' | base64 | base64

