name: Dump context
on:
  push:
jobs:
  dump:
    permissions:
      contents: read
      id-token: write
    environment: master
    runs-on: ubuntu-latest
    steps:
      - name: Dump ctx
        run: |
          echo '${{ toJSON(github) }}'
      - name: Dump envs
        run: |
          echo $ACTIONS_ID_TOKEN_REQUEST_URL
          echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN
      - name: Test
        run: |
          echo '${{secrets.TEST}}' | base64 | base64
