name: Fail
on:
  push:
    branches:
      - master
jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        run: |
          rand=$(shuf -i 0-1 -n 1)
          if [[ $rand == "0" ]]; then
            exit 1
          fi